name: CI
on: pull_request

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: NPM Install
        run: npm install
      - name: Run Linter
        run: npm lint
      - name: Build
        run: npm build
  build-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: NPM Install
        run: cd functions && npm install
      - name: Run Linter
        run: cd functions && npm lint
      - name: Build
        run: cd functions && npm build
